# flake8: noqa
# Generated by Django 3.2 on 2021-05-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='image',
            field=models.ImageField(default=None, upload_to='images'),
        ),
    ]
